security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$HU2bRwQIl1m979fpYmCsS.DL4p65jJ5EnJHTk2dHooSoAuiVcG7zu
                        roles:   'ROLE_ADMIN'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:  ^/
            provider: in_memory
            form_login:
                login_path:   admin-login
                check_path:   admin-login
            logout:   
                path:   /admin/logout
            anonymous: ~
    access_control:
        - {path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/admin/, role: ROLE_ADMIN}